### ISSUE TITLE
The app isn't working on windows

### ISSUE THREAD

**Issue by naman-gupta99** [NITKOSG/iknowsomething_backend#19]

**Comment by naman-gupta99** [comment]
Also even if this error is resolved by using some other method the config file won't work because I guess on windows process.env.NODE_ENV logs out to be dev but config[process.env.NODE_ENV] is undefined.

**Comment by war-turtle** [comment]
Gulp is not setup correctly as it is not needed, as of now. All the functionalities of the API can be used with "npm run dev".
